
`NumPy(Numerical Python)`是Python数值计算的基础包。大多数提供科学计算的包都是用NumPy的数组作为构建基础。
NumPy的部分功能如下：
- `ndarray(The N-dimensional array)`，一个具有矢量算术运算和复杂广播能力的快速且节省空间的多维数组。
- 用于对整组数据进行快速运算的标准数学函数`无需编写循环`。
- 用于读写磁盘数据的工具以及用于操作内存映射文件的工具。
- 线性代数、随机数生成以及傅里叶变换功能。
- 用于集成由C、C++、Fortran等语言编写的代码的A C API。

由于NumPy提供了一个简单易用的C API，因此很容易将数据传递给由低级语言编写的外部库，外部库也能以NumPy数组的形式将数据返回给Python。这个功能使Python成为一种包装C/C++/Fortran历史代码库的选择，并使被包装库拥有一个动态的、易用的接口。

`NumPy本身并没有提供多么高级的数据分析功能`，理解NumPy数组以及面向数组的计算将有助于你更加高效地使用诸如pandas之类的工具。因为NumPy是一个很大的题目，我会在附录A中介绍更多NumPy高级功能，比如广播。

对于大部分数据分析应用而言，最关注的功能主要集中在：
- 用于数据整理和清理、子集构造和过滤、转换等快速的矢量化数组运算。
- 常用的数组算法，如排序、唯一化、集合运算等。
- 高效的描述统计和数据聚合/摘要运算。
- 用于异构数据集的合并/连接运算的数据对齐和关系型数据运算。
- 将条件逻辑表述为数组表达式（而不是带有if-elif-else分支的循环）。
- 数据的分组运算（聚合、转换、函数应用等）。

虽然NumPy提供了通用的数值数据处理的计算基础，但大多数读者可能还是想将pandas作为统计和分析工作的基础，尤其是处理表格数据时。pandas还提供了一些NumPy所没有的领域特定的功能，如时间序列处理等。
>Python的面向数组计算可以追溯到1995年，Jim Hugunin创建了Numeric库。接下来的10年，许多科学编程社区纷纷开始使用Python的数组编程，但是进入21世纪，库的生态系统变得碎片化了。2005年，Travis Oliphant从Numeric和Numarray项目整了出了NumPy项目，进而所有社区都集合到了这个框架下。

NumPy之于数值计算特别重要的原因之一，是因为它可以高效处理大数组的数据。这是因为：
- NumPy是在一个`连续的内存块中存储数据`，独立于其他Python内置对象。NumPy的C语言编写的算法库可以操作内存，而不必进行类型检查或其它前期工作。
- 比起Python的内置序列，NumPy数组使用的内存更少。
- NumPy可以在整个数组上执行复杂的计算，而不需要Python的for循环。

要搞明白具体的性能差距，考察一个包含一百万整数的数组，和一个等价的Python列表：


In [3]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

# 两个序列同时乘以2
#%time for _ in range(10): my_arr2 = my_arr * 2
#%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

基于NumPy的算法要比纯Python快10到100倍（甚至更快），并且使用的内存更少。

# ndarray(The N-dimensional array)
NumPy最重要的一个特点就是其N维数组对象（即ndarray），该对象是一个快速而灵活的大数据集容器。你可以利用这种数组对整块数据执行一些数学运算，其语法跟标量元素之间的运算一样。

要明白Python是如何利用与标量值类似的语法进行批次计算，我先引入NumPy，然后生成一个包含随机数据的小数组：

In [4]:
import numpy as np
data = np.random.randn(2, 3)
print(data)
print(10*data)
print(data+data)

[[ 0.8188977  -1.10489225 -1.13293117]
 [-2.58335767 -1.9156472  -0.91761511]]
[[  8.18897698 -11.04892253 -11.32931167]
 [-25.83357672 -19.15647197  -9.17615113]]
[[ 1.6377954  -2.20978451 -2.26586233]
 [-5.16671534 -3.83129439 -1.83523023]]


`ndarray`是一个通用的同构数据多维容器，其中的所有元素必须是`相同类型`。每个数组都有一个`shape（一个表示各维度大小的元组）`和一个`dtype（一个用于说明数组数据类型的对象）`：

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

本章将会介绍NumPy数组的基本用法，这对于本书后面各章的理解基本够用。虽然大多数数据分析工作不需要深入理解NumPy，但是精通面向数组的编程和思维方式是成为Python科学计算牛人的一大关键步骤。
>当你在本书中看到“数组”、“NumPy数组”、"ndarray"时，基本上都指的是同一样东西，即ndarray对象。

## 创建ndarray
### `array`函数
`array`函数可以接受一切序列型的对象（包括其他数组），然后输出一个`NumPy`数组。以一个列表的转换为例：

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1.shape)
print(arr1.dtype)
arr1

(5,)
float64


array([6. , 7.5, 8. , 0. , 1. ])

嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组：

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### `zeros`、`ones`和`empty`
除`np.array`之外，还有一些函数也可以新建数组。`zeros`和`ones`分别可以创建指定长度或形状的全0或全1数组。`empty`可以创建一个没有任何具体值的数组。这些方法的入参都是一个表示形状的`元组(x, y)`：

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.empty((2, 3, 2))

array([[[1.01855798e-312, 1.06099790e-312],
        [1.01855798e-312, 9.54898106e-313],
        [1.16709769e-312, 1.01855798e-312]],

       [[1.23075756e-312, 1.16709769e-312],
        [1.10343781e-312, 9.76118064e-313],
        [1.12465777e-312, 1.90979621e-312]]])

> 注意：认为np.empty会返回全0数组的想法是不安全的。很多情况下（如前所示），它返回的都是一些未初始化的垃圾值。

arange是Python内置函数range的数组版：

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

表4-1列出了一些数组创建函数。由于NumPy关注的是数值计算，如果没有特别指定，数据类型基本都是float64（浮点数）。

![](https://obsidian-swq.oss-cn-shanghai.aliyuncs.com/20220715155334.png)

## ndarray的数据类型
dtype（数据类型）是一个特殊的对象，它含有ndarray将一块内存解释为特定数据类型所需的信息：

In [13]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [14]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

dtype是NumPy灵活交互其它系统的源泉之一。多数情况下，它们直接映射到相应的机器表示，这使得“读写磁盘上的二进制数据流”以及“集成低级语言代码（如C、Fortran）”等工作变得更加简单。

数值型dtype的命名方式相同：一个类型名（如float或int），后面跟一个用于表示各元素位长的数字。标准的双精度浮点值（即Python中的float对象）需要占用8字节（即64位），即记作float64。

表4-2列出了NumPy所支持的全部数据类型。

![](https://obsidian-swq.oss-cn-shanghai.aliyuncs.com/20220715160017.png)
![](https://obsidian-swq.oss-cn-shanghai.aliyuncs.com/20220715160052.png)

>笔记：记不住这些NumPy的dtype也没关系。通常只需要知道你所处理的数据的大致类型是浮点数、复数、整数、布尔值、字符串，还是普通的Python对象即可。当你需要控制数据在内存和磁盘中的存储方式时（尤其是对大数据集），那就得了解如何控制存储类型。


你可以通过ndarray的`astype`方法明确地将一个数组从一个dtype转换成另一个dtype：

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [16]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

如果将浮点数转换成整数，则小数部分将会被截取删除：

In [17]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [18]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

如果某字符串数组表示的全是数字，也可以用astype将其转换为数值形式：

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float) #可将np.float64简写为float

array([ 1.25, -9.6 , 42.  ])

>使用numpy.string_类型时，一定要小心，因为NumPy的字符串数据是大小固定的，发生截取时，不会发出警告。pandas提供了更多非数值数据的便利的处理方法。

数组的dtype可以传入`astype`来修改另一个数组的数据类型：

In [20]:
int_array = np.arange(10)
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
calibers

array([0.22 , 0.27 , 0.357, 0.38 , 0.44 , 0.5  ])

In [22]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

可以用简洁的类型代码，如`u4`来表示dtype：

In [23]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## NumPy数组的运算
不用编写循环即可对数据执行批量运算。NumPy用户称其为矢量化(vectorization)。

大小相等的数组之间的任何算术运算都会将运算`应用到元素级`：

In [24]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [26]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

数组与标量的算术运算会将标量值`传播到各个元素`：

In [27]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [28]:
arr ** 0.5 #开方

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [29]:
arr ** 2 #平方

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

大小相同的数组之间的比较会生成布尔值数组：

In [30]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [31]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

`不同大小的数组之间的运算叫做广播(broadcasting)`，将在附录A中对其进行详细讨论

## 基本的索引和切片
NumPy数组的索引是一个内容丰富的主题，因为选取数据子集或单个元素的方式有很多。一维数组很简单。从表面上看，它们跟Python列表的功能差不多：

In [32]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [33]:
arr[5]

5

In [34]:
arr[5:8] # end不计入

array([5, 6, 7])

In [35]:
arr[5:8] = 12 #赋值
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12])

如上所示，当你将一个标量值赋值给一个切片时，该值会`广播`到整个选区。跟列表最重要的区别在于，数组切片是原始数组的`视图`。这意味着数据不会被复制，视图上的任何修改都会直接反映到源数组上。

In [36]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

当修改`arr_slice`中的值时，原始数组`arr`也会被修改：

In [37]:
arr_slice[1] = 123 #按切片序号修改
arr

array([  0,   1,   2,   3,   4,  12, 123,  12])

切片`[ : ]`会给数组中的所有值赋值：

In [38]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64])

如果你刚开始接触NumPy，可能会对此感到惊讶（尤其是当你曾经用过其他热衷于复制数组数据的编程语言）。由于NumPy的设计目的是处理大数据，所以你可以想象一下，`假如NumPy坚持要将数据复制来复制去的话会产生何等的性能和内存问题。`
>如果你想要得到的是ndarray切片的一份副本而非视图，就需要明确地进行复制操作`copy`，例如 arr[5:8].copy()

在一个二维数组中，各索引位置上的元素不再是标量而是一维数组：

In [39]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

有两种方式可以对各个元素进行访问：

In [40]:
arr2d[0][2]

3

In [41]:
arr2d[0, 2]

3

图4-1说明了二维数组的索引方式。`轴0作为行，轴1作为列`。


![](https://obsidian-swq.oss-cn-shanghai.aliyuncs.com/20220715230730.png)


在多维数组中，如果省略了`前面的索引`，则返回对象会是一个维度低一点的ndarray（它含有高一级维度上的所有数据）。因此，在2×2×3数组arr3d中：

In [42]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


arr3d[0]是一个2×3数组，标量值和数组都可以被赋值给arr3d[0]：：

In [43]:
print('arr3d[0]: ',arr3d[0])
old_values = arr3d[0].copy()
arr3d[0] = 42 # 标量
print('arr3d: ', arr3d)
arr3d[0] = old_values # 数组
print('arr3d: ', arr3d)

arr3d[0]:  [[1 2 3]
 [4 5 6]]
arr3d:  [[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
arr3d:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


arr3d[1,0]可以访问索引以(1,0)开头的那些值（以一维数组的形式返回）：

In [44]:
arr3d[1, 0] # 第1页第0行的3列

array([7, 8, 9])

分两步进行索引的结果是相同的：

In [45]:
x = arr3d[1]
x[0]

array([7, 8, 9])

>所有这些选取数组子集的例子中，返回的数组都是视图。

## 切片索引 
`ndarray`一维对象的切片语法跟列表`List`的一维对象相同，`从0开始，区间左开右闭`。但是二维数组`arr2d`的切片方式不同：

In [46]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

二维数组的`axis=1, 行参数`可以省略，`axis=0, 列参数`不能省略。可以通过将整数索引和切片混合得到低维度的切片：

In [47]:
arr2d[:2] # arr2d的前两行  

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr2d[:,:2] # arr2d的前两列

array([[1, 2],
       [4, 5],
       [7, 8]])

In [49]:
arr2d[:2,:2] # arr2d的前两行中的前两列

array([[1, 2],
       [4, 5]])

图4-2进行了说明。“只有冒号”表示选取整个轴，因此可以像图4-2对高维轴进行切片：


![](https://obsidian-swq.oss-cn-shanghai.aliyuncs.com/20220717135901.png)


对切片表达式的赋值操作也会被扩散到整个选区：

In [52]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## 布尔型索引
假设我们有一个`存储姓名的数组`（含有重复项）以及一个用于`存储数据的数组`。使用`numpy.random`中的`randn`函数生成一些正态分布的随机数据举例说明：

In [54]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data

array([[ 8.52174088e-01, -9.52256967e-01, -1.19780602e+00,
         4.92972788e-01],
       [ 2.04844713e-01, -3.02555636e-01, -5.03005189e-01,
        -1.51315043e+00],
       [-6.46327014e-01, -1.16718875e+00, -1.69156426e-03,
        -6.13742278e-02],
       [-1.69664289e-01, -5.96638117e-01,  9.40319349e-01,
         3.22369818e+00],
       [ 9.50346846e-02,  4.90365230e-02, -1.25160558e+00,
         2.17134969e-01],
       [-6.80246233e-01, -1.02528233e+00,  5.09364574e-01,
        -6.60654112e-01],
       [ 2.83980088e-01,  2.57031401e-01,  4.45520928e-01,
        -3.67659315e-01]])

`names`数组中的每个名字都对应`data`数组中的一行，用比较运算`==`可以对数组进行矢量运算。即`names`和字符串`Bob`比较运算得到一个布尔数组，表示`names`中元素为`Bob`的位置：

In [66]:
bool_names = (names == 'Bob')
bool_names.dtype

dtype('bool')

`布尔型数组的长度必须跟被索引的轴长度一致`，可以将布尔型数组跟切片、整数混合使用：
> 注意：如果布尔型数组的长度不对，布尔型选择就会出错，因此一定要小心。

In [68]:
data[names == 'Bob', 2:]

array([[-1.19780602,  0.49297279],
       [ 0.94031935,  3.22369818]])

要选择除"Bob"以外的其他值，既可以使用不等于符号（!=），也可以通过~对条件进行否定：

In [71]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [73]:
cond = names == 'Bob'
data[~cond]

array([[ 0.20484471, -0.30255564, -0.50300519, -1.51315043],
       [-0.64632701, -1.16718875, -0.00169156, -0.06137423],
       [ 0.09503468,  0.04903652, -1.25160558,  0.21713497],
       [-0.68024623, -1.02528233,  0.50936457, -0.66065411],
       [ 0.28398009,  0.2570314 ,  0.44552093, -0.36765932]])

可以使用`&（和）、|（或）`等布尔算术运算符，进行布尔条件组合选择名字：

In [76]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[ 8.52174088e-01, -9.52256967e-01, -1.19780602e+00,
         4.92972788e-01],
       [-6.46327014e-01, -1.16718875e+00, -1.69156426e-03,
        -6.13742278e-02],
       [-1.69664289e-01, -5.96638117e-01,  9.40319349e-01,
         3.22369818e+00],
       [ 9.50346846e-02,  4.90365230e-02, -1.25160558e+00,
         2.17134969e-01]])

通过布尔型索引选取数组中的数据，创建的都是数据的副本。
>注意：Python关键字and和or在布尔型数组中无效。要使用&与|。

通过布尔型数组设置值是一种经常用到的手段。为了将data中的所有负值都设置为0，我们只需：

In [79]:
data[data < 0] = 0
data

array([[0.85217409, 0.        , 0.        , 0.49297279],
       [0.20484471, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.94031935, 3.22369818],
       [0.09503468, 0.04903652, 0.        , 0.21713497],
       [0.        , 0.        , 0.50936457, 0.        ],
       [0.28398009, 0.2570314 , 0.44552093, 0.        ]])

通过一维布尔数组设置整行或列的值也很简单：

In [81]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.20484471, 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.50936457, 0.        ],
       [0.28398009, 0.2570314 , 0.44552093, 0.        ]])

## 花式索引
花式索引（Fancy indexing）指的是NumPy中利用整数数组进行索引。假设有一个8×4数组：

In [88]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i # 对i行赋值
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可：

In [87]:
arr[[4, -3, 7]] # 负数索引从末尾选取行

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])

向ndarray传入多个索引数组，返回一个一维数组，由各维度索引组合得到的元素组成：

In [100]:
arr = np.arange(32).reshape((8, 4)) # 生成1维序列，再用reshape转为矩阵
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [101]:
arr[[1, 5, 7, 2],[0, 3, 1, 2]] # arr[1][0], arr[5][3], arr[7][1], arr[2][2]

array([ 4, 23, 29, 10])

In [104]:
arr[[1, 5, 7, 2]][:] # 该行所有列

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [106]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 数组转置和轴对换
转置是重塑的一种特殊形式，它返回的是源数据的视图（不会进行任何复制操作）。数组不仅有transpose方法，还有一个特殊的T属性：

In [107]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 计算内积

In [109]:
arr = np.random.randn(6, 3)
arr

array([[-0.11087634,  0.02651942, -0.14913416],
       [-1.09739488, -0.31422639,  0.09705514],
       [ 0.76254459,  0.28283414, -0.41610515],
       [ 2.17479099, -0.69448947,  2.09839009],
       [ 1.41483605,  0.89692717, -0.03413939],
       [-0.23191047, -1.44307959, -0.97903645]])

In [110]:
np.dot(arr.T, arr)

array([[ 8.58330271,  0.6508644 ,  4.33503594],
       [ 0.6508644 ,  3.54870934, -0.22724383],
       [ 4.33503594, -0.22724383,  5.56772302]])

对于高维数组，transpose需要得到一个由轴编号组成的元组才能对这些轴进行转置（比较费脑子）：

## transpose()

In [116]:
arr = np.array([255, 255, 255, 255, 0, 0, 0, 255,
                0, 0, 0, 255]).reshape(2, 2, -1)
arr

array([[[255, 255, 255],
        [255,   0,   0]],

       [[  0, 255,   0],
        [  0,   0, 255]]])